version: '3.8'

services:
  hop-web:
    image: apache/hop-web:latest
    container_name: hop-web
    ports:
      - "8080:8080"
    environment:
      - HOP_SERVER_USER=cluster
      - HOP_SERVER_PASS=cluster
      - HOP_AUDIT_TO_METADATA=Y
    volumes:
      - ./hop-config:/files
      - ./hop-system-config:/root/.hop
      - /mnt:/mnt:ro
      # Mapeia a pasta local de drivers ou o driver individual para o diretório correto
      - ./postgresql-42.7.3.jar:/usr/local/tomcat/jdbc-drivers/postgresql-42.7.3.jar
    networks:
      - hop-jenkins-net
    restart: unless-stopped

networks:
  hop-jenkins-net:
    external: true